{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "x4HI2mpwlrcn"
      },
      "source": [
        "##### Copyright 2019 The TensorFlow Authors."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "cellView": "form",
        "id": "679Lmwt3l1Bk"
      },
      "outputs": [],
      "source": [
        "#@title Licensed under the Apache License, Version 2.0 (the \"License\");\n",
        "# you may not use this file except in compliance with the License.\n",
        "# You may obtain a copy of the License at\n",
        "#\n",
        "# https://www.apache.org/licenses/LICENSE-2.0\n",
        "#\n",
        "# Unless required by applicable law or agreed to in writing, software\n",
        "# distributed under the License is distributed on an \"AS IS\" BASIS,\n",
        "# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n",
        "# See the License for the specific language governing permissions and\n",
        "# limitations under the License."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "DSPCom-KmApV"
      },
      "source": [
        "# Convolutional Neural Network (CNN)"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "klAltGp8ycek"
      },
      "source": [
        "<table class=\"tfo-notebook-buttons\" align=\"left\">\n",
        "  <td>\n",
        "    <a target=\"_blank\" href=\"https://www.tensorflow.org/tutorials/images/cnn\">\n",
        "    <img src=\"https://www.tensorflow.org/images/tf_logo_32px.png\" />\n",
        "    View on TensorFlow.org</a>\n",
        "  </td>\n",
        "  <td>\n",
        "    <a target=\"_blank\" href=\"https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/cnn.ipynb\">\n",
        "    <img src=\"https://www.tensorflow.org/images/colab_logo_32px.png\" />\n",
        "    Run in Google Colab</a>\n",
        "  </td>\n",
        "  <td>\n",
        "    <a target=\"_blank\" href=\"https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/cnn.ipynb\">\n",
        "    <img src=\"https://www.tensorflow.org/images/GitHub-Mark-32px.png\" />\n",
        "    View source on GitHub</a>\n",
        "  </td>\n",
        "  <td>\n",
        "    <a href=\"https://storage.googleapis.com/tensorflow_docs/docs/site/en/tutorials/images/cnn.ipynb\"><img src=\"https://www.tensorflow.org/images/download_logo_32px.png\" />Download notebook</a>\n",
        "  </td>\n",
        "</table>"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "qLGkt5qiyz4E"
      },
      "source": [
        "This tutorial demonstrates training a simple [Convolutional Neural Network](https://developers.google.com/machine-learning/glossary/#convolutional_neural_network) (CNN) to classify [CIFAR images](https://www.cs.toronto.edu/~kriz/cifar.html). Because this tutorial uses the [Keras Sequential API](https://www.tensorflow.org/guide/keras/overview), creating and training your model will take just a few lines of code.\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "m7KBpffWzlxH"
      },
      "source": [
        "### Import TensorFlow"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 1,
      "metadata": {
        "id": "iAve6DCL4JH4"
      },
      "outputs": [],
      "source": [
        "import tensorflow as tf\n",
        "\n",
        "from tensorflow.keras import datasets, layers, models\n",
        "import matplotlib.pyplot as plt\n",
        "import pickle"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "jRFxccghyMVo"
      },
      "source": [
        "### Download and prepare the CIFAR10 dataset\n",
        "\n",
        "\n",
        "The CIFAR10 dataset contains 60,000 color images in 10 classes, with 6,000 images in each class. The dataset is divided into 50,000 training images and 10,000 testing images. The classes are mutually exclusive and there is no overlap between them."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "JWoEqyMuXFF4",
        "outputId": "a18b09d4-a01f-43fc-db22-f366e58c2c08"
      },
      "outputs": [],
      "source": [
        "# (train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()\n",
        "\n",
        "# # Normalize pixel values to be between 0 and 1\n",
        "# train_images, test_images = train_images / 255.0, test_images / 255.0"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "# # Saving downloaded data for later\n",
        "# outfile = open(\"Train Data\",'wb')\n",
        "# pickle.dump((train_images,train_labels),outfile)\n",
        "# outfile.close()\n",
        "# outfile = open(\"Test Data\",'wb')\n",
        "# pickle.dump((test_images,test_labels),outfile)\n",
        "# outfile.close()"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 2,
      "metadata": {},
      "outputs": [],
      "source": [
        "(train_images, train_labels) = pickle.load(open(\"Train Data\",'rb'))\n",
        "(test_images, test_labels) = pickle.load(open(\"Test Data\",'rb'))"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "7wArwCTJJlUa"
      },
      "source": [
        "### Verify the data\n",
        "\n",
        "To verify that the dataset looks correct, let's plot the first 25 images from the training set and display the class name below each image:\n"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/",
          "height": 589
        },
        "id": "K3PAELE2eSU9",
        "outputId": "e501f134-41b7-4156-ec4c-d67571f4ce7b"
      },
      "outputs": [],
      "source": [
        "class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',\n",
        "               'dog', 'frog', 'horse', 'ship', 'truck']\n",
        "\n",
        "plt.figure(figsize=(10,10))\n",
        "for i in range(25):\n",
        "    plt.subplot(5,5,i+1)\n",
        "    plt.xticks([])\n",
        "    plt.yticks([])\n",
        "    plt.grid(False)\n",
        "    plt.imshow(train_images[i])\n",
        "    # The CIFAR labels happen to be arrays, \n",
        "    # which is why you need the extra index\n",
        "    plt.xlabel(class_names[train_labels[i][0]])\n",
        "plt.show()"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "Oewp-wYg31t9"
      },
      "source": [
        "### Create the convolutional base"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "3hQvqXpNyN3x"
      },
      "source": [
        "The 6 lines of code below define the convolutional base using a common pattern: a stack of [Conv2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D) and [MaxPooling2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/MaxPool2D) layers.\n",
        "\n",
        "As input, a CNN takes tensors of shape (image_height, image_width, color_channels), ignoring the batch size. If you are new to these dimensions, color_channels refers to (R,G,B). In this example, you will configure your CNN to process inputs of shape (32, 32, 3), which is the format of CIFAR images. You can do this by passing the argument `input_shape` to your first layer.\n"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "lvDVFkg-2DPm"
      },
      "source": [
        "Let's display the architecture of your model so far:"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "_j-AXYeZ2GO5"
      },
      "source": [
        "Above, you can see that the output of every Conv2D and MaxPooling2D layer is a 3D tensor of shape (height, width, channels). The width and height dimensions tend to shrink as you go deeper in the network. The number of output channels for each Conv2D layer is controlled by the first argument (e.g., 32 or 64). Typically,  as the width and height shrink, you can afford (computationally) to add more output channels in each Conv2D layer."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "_v8sVOtG37bT"
      },
      "source": [
        "### Add Dense layers on top\n",
        "\n",
        "To complete the model, you will feed the last output tensor from the convolutional base (of shape (4, 4, 64)) into one or more Dense layers to perform classification. Dense layers take vectors as input (which are 1D), while the current output is a 3D tensor. First, you will flatten (or unroll) the 3D output to 1D,  then add one or more Dense layers on top. CIFAR has 10 output classes, so you use a final Dense layer with 10 outputs."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "ipGiQMcR4Gtq"
      },
      "source": [
        "Here's the complete architecture of your model:"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "xNKXi-Gy3RO-"
      },
      "source": [
        "The network summary shows that (4, 4, 64) outputs were flattened into vectors of shape (1024) before going through two Dense layers."
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "P3odqfHP4M67"
      },
      "source": [
        "### Compile and train the model"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "jKgyC5K_4O0d"
      },
      "source": [
        "### Evaluate the model"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 3,
      "metadata": {},
      "outputs": [],
      "source": [
        "# strategy = tf.distribute.MirroredStrategy()\n",
        "# options = tf.data.Options()\n",
        "# options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA\n",
        "# dataset = tf.data.Dataset.from_tensor_slices((train_images,train_labels,dtype='float64'))\n",
        "# dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))\n",
        "# dataset = dataset.with_options(options).batch(32)\n",
        "\n",
        "def base_model():\n",
        "    # with strategy.scope():\n",
        "    model = models.Sequential()\n",
        "    model.add(layers.Conv2D(32, (3, 3), activation='relu'))\n",
        "    model.add(layers.MaxPooling2D((2, 2)))\n",
        "    model.add(layers.Conv2D(64, (3, 3), activation='relu'))\n",
        "    model.add(layers.MaxPooling2D((2, 2)))\n",
        "    model.add(layers.Conv2D(64, (3, 3), activation='relu'))\n",
        "    model.add(layers.Flatten())\n",
        "    model.add(layers.Dense(64, activation='relu'))\n",
        "    model.add(layers.Dense(10, activation='softmax'))\n",
        "    return model\n",
        "def flatten_model(model:models.Sequential):\n",
        "    # with strategy.scope():\n",
        "    model.add(layers.Flatten())\n",
        "    model.add(layers.Dense(128, activation='relu'))\n",
        "    model.add(layers.Dense(10, activation='softmax'))\n",
        "    # model.summary()\n",
        "    model.compile(optimizer='adam',\n",
        "        loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),\n",
        "        metrics=['accuracy'])    \n",
        "    return model    \n",
        "def dropout_model():\n",
        "    # with strategy.scope():\n",
        "    model = models.Sequential()\n",
        "    model.add(layers.Conv2D(32, (3, 3), activation='relu'))\n",
        "    model.add(layers.MaxPooling2D((2, 2)))\n",
        "    model.add(layers.Dropout(.2))\n",
        "\n",
        "    model.add(layers.Conv2D(64, (3, 3), activation='relu'))\n",
        "    model.add(layers.MaxPooling2D((2, 2)))\n",
        "    model.add(layers.Dropout(.2))\n",
        "\n",
        "    model.add(layers.Conv2D(64, (3, 3), activation='relu'))\n",
        "    model.add(layers.MaxPooling2D((2, 2)))\n",
        "    model.add(layers.Dropout(.2))\n",
        "\n",
        "    model.add(layers.Flatten())\n",
        "    model.add(layers.Dense(128, activation='relu'))\n",
        "    model.add(layers.Dense(10, activation='softmax'))\n",
        "    return model\n",
        "def augment_model():\n",
        "    # with strategy.scope():\n",
        "    model = models.Sequential()\n",
        "    model.add(layers.RandomFlip(\"horizontal\",input_shape=(32,32,3)))\n",
        "    model.add(layers.RandomRotation(0.1))\n",
        "    model.add(layers.RandomZoom(0.1))\n",
        "    model.add(layers.Conv2D(32, (3, 3), activation='relu'))\n",
        "    model.add(layers.MaxPooling2D((2, 2)))\n",
        "    model.add(layers.Dropout(.2))\n",
        "\n",
        "    model.add(layers.Conv2D(64, (3, 3), activation='relu'))\n",
        "    model.add(layers.MaxPooling2D((2, 2)))\n",
        "    model.add(layers.Dropout(.2))\n",
        "\n",
        "    model.add(layers.Conv2D(64, (3, 3), activation='relu'))\n",
        "    model.add(layers.MaxPooling2D((2, 2)))\n",
        "    model.add(layers.Dropout(.2))\n",
        "\n",
        "    model.add(layers.Flatten())\n",
        "\n",
        "    model.add(layers.Dense(128, activation='relu'))\n",
        "    model.add(layers.Dense(10, activation='softmax'))\n",
        "\n",
        "    return model\n",
        "def batch_normalize_model():\n",
        "    # with strategy.scope():\n",
        "    model = models.Sequential()\n",
        "    model.add(layers.RandomFlip(\"horizontal\",input_shape=(32,32,3)))\n",
        "    model.add(layers.RandomRotation(0.1))\n",
        "    model.add(layers.RandomZoom(0.1))\n",
        "    model.add(layers.Conv2D(32, (3, 3), activation='relu'))\n",
        "    model.add(layers.BatchNormalization())\n",
        "\n",
        "    model.add(layers.MaxPooling2D((2, 2)))\n",
        "    model.add(layers.Dropout(.2))\n",
        "\n",
        "    model.add(layers.Conv2D(64, (3, 3), activation='relu'))\n",
        "    model.add(layers.BatchNormalization())\n",
        "\n",
        "    model.add(layers.MaxPooling2D((2, 2)))\n",
        "    model.add(layers.Dropout(.2))\n",
        "\n",
        "    model.add(layers.Conv2D(64, (3, 3), activation='relu'))\n",
        "    model.add(layers.BatchNormalization())\n",
        "    model.add(layers.MaxPooling2D((2, 2)))\n",
        "    model.add(layers.Dropout(.2))\n",
        "\n",
        "    model.add(layers.Flatten())\n",
        "\n",
        "    model.add(layers.Dense(128, activation='relu'))\n",
        "    model.add(layers.Dense(10, activation='softmax'))\n",
        "    return model\n",
        "\n",
        "def ReshapeLayer(x):\n",
        "    \n",
        "    shape = x.shape\n",
        "    \n",
        "    # 1 possibility: H,W*channel\n",
        "    reshape = layers.Reshape((shape[1],shape[2]*shape[3]))(x)\n",
        "    \n",
        "    # 2 possibility: W,H*channel\n",
        "    # transpose = Permute((2,1,3))(x)\n",
        "    # reshape = Reshape((shape[1],shape[2]*shape[3]))(transpose)\n",
        "    \n",
        "    return reshape\n",
        "def lstm_model():\n",
        "    # with strategy.scope():\n",
        "    model = models.Sequential()\n",
        "    model.add(layers.RandomFlip(\"horizontal_and_vertical\",input_shape=(32,32,3)))\n",
        "    model.add(layers.RandomRotation(0.1))\n",
        "    model.add(layers.RandomZoom(0.1))\n",
        "    weight_decay = 1e-4\n",
        "    model.add(layers.Conv2D(32, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay), activation='selu'))\n",
        "    model.add(layers.BatchNormalization())\n",
        "    model.add(layers.Conv2D(32, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay), activation='selu'))\n",
        "    model.add(layers.BatchNormalization())\n",
        "\n",
        "    model.add(layers.MaxPooling2D(pool_size=(2,2)))\n",
        "    model.add(layers.Dropout(0.2))\n",
        "\n",
        "    model.add(layers.Conv2D(64, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay), activation='selu'))\n",
        "    model.add(layers.BatchNormalization())\n",
        "    model.add(layers.Conv2D(64, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay), activation='selu'))\n",
        "    model.add(layers.BatchNormalization())\n",
        "    model.add(layers.MaxPooling2D(pool_size=(2,2)))\n",
        "    model.add(layers.Dropout(0.3))\n",
        "    # model.add(layers.LSTM(200))\n",
        "    model.add(layers.Conv2D(128, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay), activation='selu'))\n",
        "    model.add(layers.BatchNormalization())\n",
        "    model.add(layers.Conv2D(128, (3,3), padding='same', kernel_regularizer=tf.keras.regularizers.l2(weight_decay), activation='selu'))\n",
        "    model.add(layers.BatchNormalization())\n",
        "    model.add(layers.MaxPooling2D(pool_size=(2,2)))\n",
        "    model.add(layers.Dropout(0.4))\n",
        "\n",
        "        \n",
        "    model.add(layers.Flatten())\n",
        "\n",
        "    # model.add(layers.Dense(256, activation='selu'))\n",
        "    model.add(layers.Dense(64, activation='selu'))\n",
        "\n",
        "    model.add(layers.BatchNormalization())\n",
        "\n",
        "    model.add(layers.Dense(10))\n",
        "    return model\n",
        "def execute_model(model:models.Sequential):\n",
        "    model.compile(optimizer='adam',\n",
        "            loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),\n",
        "            metrics=['accuracy'])    \n",
        "    history = model.fit(train_images, train_labels, epochs=200,\n",
        "                    validation_data=(test_images, test_labels))\n",
        "    plt.plot(history.history['accuracy'], label='accuracy')\n",
        "    plt.plot(history.history['val_accuracy'], label = 'val_accuracy')\n",
        "    plt.xlabel('Epoch')\n",
        "    plt.ylabel('Accuracy')\n",
        "    plt.ylim([0.5, 1])\n",
        "    plt.legend(loc='lower right')\n",
        "    plt.show()\n",
        "    _, test_acc = model.evaluate(test_images,  test_labels, verbose=2)\n",
        "    return test_acc"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "8cfJ8AR03gT5"
      },
      "source": [
        "Your simple CNN has achieved a test accuracy of over 70%. Not bad for a few lines of code! For another CNN style, check out the [TensorFlow 2 quickstart for experts](https://www.tensorflow.org/tutorials/quickstart/advanced) example that uses the Keras subclassing API and `tf.GradientTape`."
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": [
        "for (generateModel, model_name) in zip([base_model, dropout_model, augment_model, batch_normalize_model, lstm_model],[\n",
        "                            \"base_model\" ,\"dropout_model\" ,\"augment_model\" ,\"batch_normalize_model\" ,\"lstm_model\"]):\n",
        "    model = generateModel()\n",
        "    model = flatten_model(model)\n",
        "    print(f\"Executing {model_name} Model\")\n",
        "    acc = execute_model(model)\n",
        "    print(f\"The {model_name} model has an accuracy of {acc}\")"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 4,
      "metadata": {},
      "outputs": [
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "2021-11-15 06:19:48.268875: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:48.269252: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:48.274994: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:48.275399: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:48.275748: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:48.276088: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:48.276774: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA\n",
            "To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.\n",
            "2021-11-15 06:19:48.515778: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:48.516131: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:48.516438: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:48.516739: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:48.517042: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:48.517347: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:49.408312: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:49.408721: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:49.409043: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:49.409355: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:49.409679: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:49.409959: I tensorflow/core/common_runtime/gpu/gpu_process_state.cc:214] Using CUDA malloc Async allocator for GPU: 0\n",
            "2021-11-15 06:19:49.410105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 696 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070 Ti, pci bus id: 0000:0a:00.0, compute capability: 8.6\n",
            "2021-11-15 06:19:49.410699: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:939] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero\n",
            "2021-11-15 06:19:49.411017: I tensorflow/core/common_runtime/gpu/gpu_process_state.cc:214] Using CUDA malloc Async allocator for GPU: 1\n",
            "2021-11-15 06:19:49.411063: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1525] Created device /job:localhost/replica:0/task:0/device:GPU:1 with 9332 MB memory:  -> device: 1, name: NVIDIA GeForce RTX 2080 Ti, pci bus id: 0000:05:00.0, compute capability: 7.5\n"
          ]
        },
        {
          "name": "stdout",
          "output_type": "stream",
          "text": [
            "Epoch 1/200\n"
          ]
        },
        {
          "name": "stderr",
          "output_type": "stream",
          "text": [
            "2021-11-15 06:19:56.778602: I tensorflow/stream_executor/cuda/cuda_dnn.cc:366] Loaded cuDNN version 8100\n",
            "2021-11-15 06:19:57.096387: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 20971520 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)\n",
            " Reported by CUDA: Free memory/Total memory: 11730944/8369668096\n",
            "2021-11-15 06:19:57.096444: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                       730005504\n",
            "InUse:                       626377164\n",
            "MaxInUse:                    626377164\n",
            "NumAllocs:                         301\n",
            "MaxAllocSize:                614400000\n",
            "Reserved:                            0\n",
            "PeakReserved:                        0\n",
            "LargestFreeBlock:                    0\n",
            "\n",
            "2021-11-15 06:19:57.096463: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;\n",
            "2021-11-15 06:19:57.096470: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 58\n",
            "2021-11-15 06:19:57.096474: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 10\n",
            "2021-11-15 06:19:57.096478: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 24, 3\n",
            "2021-11-15 06:19:57.096482: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 40, 3\n",
            "2021-11-15 06:19:57.096486: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 128, 23\n",
            "2021-11-15 06:19:57.096490: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 256, 34\n",
            "2021-11-15 06:19:57.096494: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 512, 22\n",
            "2021-11-15 06:19:57.096498: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1\n",
            "2021-11-15 06:19:57.096502: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 2560, 3\n",
            "2021-11-15 06:19:57.096506: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 3456, 6\n",
            "2021-11-15 06:19:57.096510: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 36864, 5\n",
            "2021-11-15 06:19:57.096513: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 50000, 1\n",
            "2021-11-15 06:19:57.096517: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 73728, 5\n",
            "2021-11-15 06:19:57.096521: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 147456, 5\n",
            "2021-11-15 06:19:57.096525: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 294912, 5\n",
            "2021-11-15 06:19:57.096529: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 393216, 1\n",
            "2021-11-15 06:19:57.096532: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 524288, 3\n",
            "2021-11-15 06:19:57.096536: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 589824, 5\n",
            "2021-11-15 06:19:57.096540: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4194304, 1\n",
            "2021-11-15 06:19:57.096544: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 614400000, 1\n",
            "2021-11-15 06:19:57.096559: W tensorflow/core/kernels/gpu_utils.cc:49] Failed to allocate memory for convolution redzone checking; skipping this check. This is benign and only means that we won't check cudnn for out-of-bounds reads and writes. This message will only be printed once.\n",
            "2021-11-15 06:19:57.116166: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 20316160 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)\n",
            " Reported by CUDA: Free memory/Total memory: 3342336/8369668096\n",
            "2021-11-15 06:19:57.116198: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                       730005504\n",
            "InUse:                       626377164\n",
            "MaxInUse:                    626377164\n",
            "NumAllocs:                         301\n",
            "MaxAllocSize:                614400000\n",
            "Reserved:                            0\n",
            "PeakReserved:                        0\n",
            "LargestFreeBlock:                    0\n",
            "\n",
            "2021-11-15 06:19:57.116213: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;\n",
            "2021-11-15 06:19:57.116218: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 58\n",
            "2021-11-15 06:19:57.116222: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 10\n",
            "2021-11-15 06:19:57.116226: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 24, 3\n",
            "2021-11-15 06:19:57.116230: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 40, 3\n",
            "2021-11-15 06:19:57.116233: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 128, 23\n",
            "2021-11-15 06:19:57.116237: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 256, 34\n",
            "2021-11-15 06:19:57.116241: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 512, 22\n",
            "2021-11-15 06:19:57.116245: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1\n",
            "2021-11-15 06:19:57.116248: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 2560, 3\n",
            "2021-11-15 06:19:57.116252: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 3456, 6\n",
            "2021-11-15 06:19:57.116256: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 36864, 5\n",
            "2021-11-15 06:19:57.116260: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 50000, 1\n",
            "2021-11-15 06:19:57.116264: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 73728, 5\n",
            "2021-11-15 06:19:57.116268: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 147456, 5\n",
            "2021-11-15 06:19:57.116272: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 294912, 5\n",
            "2021-11-15 06:19:57.116276: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 393216, 1\n",
            "2021-11-15 06:19:57.116280: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 524288, 3\n",
            "2021-11-15 06:19:57.116283: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 589824, 5\n",
            "2021-11-15 06:19:57.116287: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4194304, 1\n",
            "2021-11-15 06:19:57.116290: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 614400000, 1\n",
            "2021-11-15 06:19:57.116575: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 20316160 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)\n",
            " Reported by CUDA: Free memory/Total memory: 3342336/8369668096\n",
            "2021-11-15 06:19:57.116603: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                       730005504\n",
            "InUse:                       626377164\n",
            "MaxInUse:                    626377164\n",
            "NumAllocs:                         301\n",
            "MaxAllocSize:                614400000\n",
            "Reserved:                            0\n",
            "PeakReserved:                        0\n",
            "LargestFreeBlock:                    0\n",
            "\n",
            "2021-11-15 06:19:57.116616: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;\n",
            "2021-11-15 06:19:57.116625: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 58\n",
            "2021-11-15 06:19:57.116629: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 10\n",
            "2021-11-15 06:19:57.116633: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 24, 3\n",
            "2021-11-15 06:19:57.116636: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 40, 3\n",
            "2021-11-15 06:19:57.116640: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 128, 23\n",
            "2021-11-15 06:19:57.116644: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 256, 34\n",
            "2021-11-15 06:19:57.116647: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 512, 22\n",
            "2021-11-15 06:19:57.116651: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1\n",
            "2021-11-15 06:19:57.116655: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 2560, 3\n",
            "2021-11-15 06:19:57.116659: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 3456, 6\n",
            "2021-11-15 06:19:57.116663: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 36864, 5\n",
            "2021-11-15 06:19:57.116667: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 50000, 1\n",
            "2021-11-15 06:19:57.116670: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 73728, 5\n",
            "2021-11-15 06:19:57.116674: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 147456, 5\n",
            "2021-11-15 06:19:57.116677: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 294912, 5\n",
            "2021-11-15 06:19:57.116681: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 393216, 1\n",
            "2021-11-15 06:19:57.116684: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 524288, 3\n",
            "2021-11-15 06:19:57.116688: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 589824, 5\n",
            "2021-11-15 06:19:57.116692: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4194304, 1\n",
            "2021-11-15 06:19:57.116696: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 614400000, 1\n",
            "2021-11-15 06:19:57.117019: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 51383680 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)\n",
            " Reported by CUDA: Free memory/Total memory: 3342336/8369668096\n",
            "2021-11-15 06:19:57.117035: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                       730005504\n",
            "InUse:                       626377164\n",
            "MaxInUse:                    626377164\n",
            "NumAllocs:                         301\n",
            "MaxAllocSize:                614400000\n",
            "Reserved:                            0\n",
            "PeakReserved:                        0\n",
            "LargestFreeBlock:                    0\n",
            "\n",
            "2021-11-15 06:19:57.117045: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;\n",
            "2021-11-15 06:19:57.117050: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 58\n",
            "2021-11-15 06:19:57.117054: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 10\n",
            "2021-11-15 06:19:57.117059: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 24, 3\n",
            "2021-11-15 06:19:57.117063: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 40, 3\n",
            "2021-11-15 06:19:57.117067: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 128, 23\n",
            "2021-11-15 06:19:57.117071: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 256, 34\n",
            "2021-11-15 06:19:57.117075: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 512, 22\n",
            "2021-11-15 06:19:57.117079: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1\n",
            "2021-11-15 06:19:57.117083: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 2560, 3\n",
            "2021-11-15 06:19:57.117087: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 3456, 6\n",
            "2021-11-15 06:19:57.117090: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 36864, 5\n",
            "2021-11-15 06:19:57.117094: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 50000, 1\n",
            "2021-11-15 06:19:57.117098: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 73728, 5\n",
            "2021-11-15 06:19:57.117102: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 147456, 5\n",
            "2021-11-15 06:19:57.117105: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 294912, 5\n",
            "2021-11-15 06:19:57.117109: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 393216, 1\n",
            "2021-11-15 06:19:57.117113: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 524288, 3\n",
            "2021-11-15 06:19:57.117117: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 589824, 5\n",
            "2021-11-15 06:19:57.117120: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4194304, 1\n",
            "2021-11-15 06:19:57.117124: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 614400000, 1\n",
            "2021-11-15 06:19:57.117414: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 51383680 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)\n",
            " Reported by CUDA: Free memory/Total memory: 3342336/8369668096\n",
            "2021-11-15 06:19:57.117431: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                       730005504\n",
            "InUse:                       626377164\n",
            "MaxInUse:                    626377164\n",
            "NumAllocs:                         301\n",
            "MaxAllocSize:                614400000\n",
            "Reserved:                            0\n",
            "PeakReserved:                        0\n",
            "LargestFreeBlock:                    0\n",
            "\n",
            "2021-11-15 06:19:57.117442: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;\n",
            "2021-11-15 06:19:57.117448: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 58\n",
            "2021-11-15 06:19:57.117452: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 10\n",
            "2021-11-15 06:19:57.117456: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 24, 3\n",
            "2021-11-15 06:19:57.117460: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 40, 3\n",
            "2021-11-15 06:19:57.117465: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 128, 23\n",
            "2021-11-15 06:19:57.117469: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 256, 34\n",
            "2021-11-15 06:19:57.117473: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 512, 22\n",
            "2021-11-15 06:19:57.117478: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1\n",
            "2021-11-15 06:19:57.117482: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 2560, 3\n",
            "2021-11-15 06:19:57.117486: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 3456, 6\n",
            "2021-11-15 06:19:57.117490: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 36864, 5\n",
            "2021-11-15 06:19:57.117494: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 50000, 1\n",
            "2021-11-15 06:19:57.117498: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 73728, 5\n",
            "2021-11-15 06:19:57.117502: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 147456, 5\n",
            "2021-11-15 06:19:57.117506: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 294912, 5\n",
            "2021-11-15 06:19:57.117510: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 393216, 1\n",
            "2021-11-15 06:19:57.117514: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 524288, 3\n",
            "2021-11-15 06:19:57.117518: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 589824, 5\n",
            "2021-11-15 06:19:57.117522: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4194304, 1\n",
            "2021-11-15 06:19:57.117526: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 614400000, 1\n",
            "2021-11-15 06:19:57.147934: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 16798208 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)\n",
            " Reported by CUDA: Free memory/Total memory: 3342336/8369668096\n",
            "2021-11-15 06:19:57.147977: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                       730005504\n",
            "InUse:                       626377164\n",
            "MaxInUse:                    626377164\n",
            "NumAllocs:                         301\n",
            "MaxAllocSize:                614400000\n",
            "Reserved:                            0\n",
            "PeakReserved:                        0\n",
            "LargestFreeBlock:                    0\n",
            "\n",
            "2021-11-15 06:19:57.147993: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;\n",
            "2021-11-15 06:19:57.147999: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 58\n",
            "2021-11-15 06:19:57.148004: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 10\n",
            "2021-11-15 06:19:57.148008: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 24, 3\n",
            "2021-11-15 06:19:57.148012: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 40, 3\n",
            "2021-11-15 06:19:57.148016: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 128, 23\n",
            "2021-11-15 06:19:57.148020: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 256, 34\n",
            "2021-11-15 06:19:57.148025: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 512, 22\n",
            "2021-11-15 06:19:57.148029: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1\n",
            "2021-11-15 06:19:57.148033: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 2560, 3\n",
            "2021-11-15 06:19:57.148037: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 3456, 6\n",
            "2021-11-15 06:19:57.148041: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 36864, 5\n",
            "2021-11-15 06:19:57.148045: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 50000, 1\n",
            "2021-11-15 06:19:57.148049: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 73728, 5\n",
            "2021-11-15 06:19:57.148054: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 147456, 5\n",
            "2021-11-15 06:19:57.148058: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 294912, 5\n",
            "2021-11-15 06:19:57.148062: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 393216, 1\n",
            "2021-11-15 06:19:57.148066: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 524288, 3\n",
            "2021-11-15 06:19:57.148070: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 589824, 5\n",
            "2021-11-15 06:19:57.148074: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4194304, 1\n",
            "2021-11-15 06:19:57.148078: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 614400000, 1\n",
            "2021-11-15 06:19:57.148513: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 16798208 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)\n",
            " Reported by CUDA: Free memory/Total memory: 3342336/8369668096\n",
            "2021-11-15 06:19:57.148528: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                       730005504\n",
            "InUse:                       626377164\n",
            "MaxInUse:                    626377164\n",
            "NumAllocs:                         301\n",
            "MaxAllocSize:                614400000\n",
            "Reserved:                            0\n",
            "PeakReserved:                        0\n",
            "LargestFreeBlock:                    0\n",
            "\n",
            "2021-11-15 06:19:57.148538: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;\n",
            "2021-11-15 06:19:57.148543: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 58\n",
            "2021-11-15 06:19:57.148546: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 10\n",
            "2021-11-15 06:19:57.148550: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 24, 3\n",
            "2021-11-15 06:19:57.148554: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 40, 3\n",
            "2021-11-15 06:19:57.148558: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 128, 23\n",
            "2021-11-15 06:19:57.148562: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 256, 34\n",
            "2021-11-15 06:19:57.148566: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 512, 22\n",
            "2021-11-15 06:19:57.148570: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1\n",
            "2021-11-15 06:19:57.148574: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 2560, 3\n",
            "2021-11-15 06:19:57.148578: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 3456, 6\n",
            "2021-11-15 06:19:57.148582: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 36864, 5\n",
            "2021-11-15 06:19:57.148586: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 50000, 1\n",
            "2021-11-15 06:19:57.148607: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 73728, 5\n",
            "2021-11-15 06:19:57.148616: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 147456, 5\n",
            "2021-11-15 06:19:57.148628: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 294912, 5\n",
            "2021-11-15 06:19:57.148633: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 393216, 1\n",
            "2021-11-15 06:19:57.148637: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 524288, 3\n",
            "2021-11-15 06:19:57.148641: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 589824, 5\n",
            "2021-11-15 06:19:57.148645: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4194304, 1\n",
            "2021-11-15 06:19:57.148648: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 614400000, 1\n",
            "2021-11-15 06:19:57.148959: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 26943488 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)\n",
            " Reported by CUDA: Free memory/Total memory: 3342336/8369668096\n",
            "2021-11-15 06:19:57.148976: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                       730005504\n",
            "InUse:                       626377164\n",
            "MaxInUse:                    626377164\n",
            "NumAllocs:                         301\n",
            "MaxAllocSize:                614400000\n",
            "Reserved:                            0\n",
            "PeakReserved:                        0\n",
            "LargestFreeBlock:                    0\n",
            "\n",
            "2021-11-15 06:19:57.148987: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;\n",
            "2021-11-15 06:19:57.148992: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 58\n",
            "2021-11-15 06:19:57.148998: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 10\n",
            "2021-11-15 06:19:57.149002: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 24, 3\n",
            "2021-11-15 06:19:57.149006: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 40, 3\n",
            "2021-11-15 06:19:57.149010: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 128, 23\n",
            "2021-11-15 06:19:57.149014: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 256, 34\n",
            "2021-11-15 06:19:57.149018: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 512, 22\n",
            "2021-11-15 06:19:57.149022: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1\n",
            "2021-11-15 06:19:57.149026: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 2560, 3\n",
            "2021-11-15 06:19:57.149030: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 3456, 6\n",
            "2021-11-15 06:19:57.149034: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 36864, 5\n",
            "2021-11-15 06:19:57.149038: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 50000, 1\n",
            "2021-11-15 06:19:57.149042: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 73728, 5\n",
            "2021-11-15 06:19:57.149047: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 147456, 5\n",
            "2021-11-15 06:19:57.149051: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 294912, 5\n",
            "2021-11-15 06:19:57.149055: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 393216, 1\n",
            "2021-11-15 06:19:57.149059: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 524288, 3\n",
            "2021-11-15 06:19:57.149063: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 589824, 5\n",
            "2021-11-15 06:19:57.149067: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4194304, 1\n",
            "2021-11-15 06:19:57.149071: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 614400000, 1\n",
            "2021-11-15 06:19:57.149364: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 26943488 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)\n",
            " Reported by CUDA: Free memory/Total memory: 3342336/8369668096\n",
            "2021-11-15 06:19:57.149379: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                       730005504\n",
            "InUse:                       626377164\n",
            "MaxInUse:                    626377164\n",
            "NumAllocs:                         301\n",
            "MaxAllocSize:                614400000\n",
            "Reserved:                            0\n",
            "PeakReserved:                        0\n",
            "LargestFreeBlock:                    0\n",
            "\n",
            "2021-11-15 06:19:57.149390: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;\n",
            "2021-11-15 06:19:57.149395: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 58\n",
            "2021-11-15 06:19:57.149399: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 10\n",
            "2021-11-15 06:19:57.149403: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 24, 3\n",
            "2021-11-15 06:19:57.149407: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 40, 3\n",
            "2021-11-15 06:19:57.149412: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 128, 23\n",
            "2021-11-15 06:19:57.149416: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 256, 34\n",
            "2021-11-15 06:19:57.149420: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 512, 22\n",
            "2021-11-15 06:19:57.149423: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1\n",
            "2021-11-15 06:19:57.149427: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 2560, 3\n",
            "2021-11-15 06:19:57.149432: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 3456, 6\n",
            "2021-11-15 06:19:57.149435: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 36864, 5\n",
            "2021-11-15 06:19:57.149439: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 50000, 1\n",
            "2021-11-15 06:19:57.149443: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 73728, 5\n",
            "2021-11-15 06:19:57.149447: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 147456, 5\n",
            "2021-11-15 06:19:57.149451: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 294912, 5\n",
            "2021-11-15 06:19:57.149455: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 393216, 1\n",
            "2021-11-15 06:19:57.149459: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 524288, 3\n",
            "2021-11-15 06:19:57.149463: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 589824, 5\n",
            "2021-11-15 06:19:57.149466: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4194304, 1\n",
            "2021-11-15 06:19:57.149470: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 614400000, 1\n",
            "2021-11-15 06:19:57.149759: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 27112960 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)\n",
            " Reported by CUDA: Free memory/Total memory: 3342336/8369668096\n",
            "2021-11-15 06:19:57.149775: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                       730005504\n",
            "InUse:                       626377164\n",
            "MaxInUse:                    626377164\n",
            "NumAllocs:                         301\n",
            "MaxAllocSize:                614400000\n",
            "Reserved:                            0\n",
            "PeakReserved:                        0\n",
            "LargestFreeBlock:                    0\n",
            "\n",
            "2021-11-15 06:19:57.149786: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;\n",
            "2021-11-15 06:19:57.149791: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 58\n",
            "2021-11-15 06:19:57.149795: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 10\n",
            "2021-11-15 06:19:57.149799: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 24, 3\n",
            "2021-11-15 06:19:57.149803: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 40, 3\n",
            "2021-11-15 06:19:57.149807: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 128, 23\n",
            "2021-11-15 06:19:57.149811: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 256, 34\n",
            "2021-11-15 06:19:57.149815: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 512, 22\n",
            "2021-11-15 06:19:57.149819: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1\n",
            "2021-11-15 06:19:57.149823: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 2560, 3\n",
            "2021-11-15 06:19:57.149826: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 3456, 6\n",
            "2021-11-15 06:19:57.149831: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 36864, 5\n",
            "2021-11-15 06:19:57.149835: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 50000, 1\n",
            "2021-11-15 06:19:57.149839: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 73728, 5\n",
            "2021-11-15 06:19:57.149843: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 147456, 5\n",
            "2021-11-15 06:19:57.149847: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 294912, 5\n",
            "2021-11-15 06:19:57.149850: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 393216, 1\n",
            "2021-11-15 06:19:57.149854: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 524288, 3\n",
            "2021-11-15 06:19:57.149858: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 589824, 5\n",
            "2021-11-15 06:19:57.149862: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4194304, 1\n",
            "2021-11-15 06:19:57.149866: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 614400000, 1\n",
            "2021-11-15 06:19:57.150142: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:288] gpu_async_0 cuMemAllocAsync failed to allocate 27112960 bytes: CUDA error: out of memory (CUDA_ERROR_OUT_OF_MEMORY)\n",
            " Reported by CUDA: Free memory/Total memory: 3342336/8369668096\n",
            "2021-11-15 06:19:57.150154: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:293] Stats: Limit:                       730005504\n",
            "InUse:                       626377164\n",
            "MaxInUse:                    626377164\n",
            "NumAllocs:                         301\n",
            "MaxAllocSize:                614400000\n",
            "Reserved:                            0\n",
            "PeakReserved:                        0\n",
            "LargestFreeBlock:                    0\n",
            "\n",
            "2021-11-15 06:19:57.150165: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:56] Histogram of current allocation: (allocation_size_in_bytes, nb_allocation_of_that_sizes), ...;\n",
            "2021-11-15 06:19:57.150169: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4, 58\n",
            "2021-11-15 06:19:57.150173: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 8, 10\n",
            "2021-11-15 06:19:57.150177: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 24, 3\n",
            "2021-11-15 06:19:57.150181: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 40, 3\n",
            "2021-11-15 06:19:57.150187: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 128, 23\n",
            "2021-11-15 06:19:57.150191: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 256, 34\n",
            "2021-11-15 06:19:57.150195: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 512, 22\n",
            "2021-11-15 06:19:57.150199: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 1028, 1\n",
            "2021-11-15 06:19:57.150203: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 2560, 3\n",
            "2021-11-15 06:19:57.150207: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 3456, 6\n",
            "2021-11-15 06:19:57.150211: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 36864, 5\n",
            "2021-11-15 06:19:57.150214: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 50000, 1\n",
            "2021-11-15 06:19:57.150218: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 73728, 5\n",
            "2021-11-15 06:19:57.150222: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 147456, 5\n",
            "2021-11-15 06:19:57.150226: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 294912, 5\n",
            "2021-11-15 06:19:57.150230: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 393216, 1\n",
            "2021-11-15 06:19:57.150234: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 524288, 3\n",
            "2021-11-15 06:19:57.150238: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 589824, 5\n",
            "2021-11-15 06:19:57.150242: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 4194304, 1\n",
            "2021-11-15 06:19:57.150245: E tensorflow/core/common_runtime/gpu/gpu_cudamallocasync_allocator.cc:59] 614400000, 1\n",
            "2021-11-15 06:19:57.158626: E tensorflow/stream_executor/cuda/cuda_blas.cc:226] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED\n",
            "2021-11-15 06:19:57.158899: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at conv_ops.cc:1120 : NOT_FOUND: No algorithm worked!\n"
          ]
        },
        {
          "ename": "NotFoundError",
          "evalue": " No algorithm worked!\n\t [[node sequential/conv2d/Conv2D\n (defined at /usr/local/lib/python3.8/dist-packages/keras/layers/convolutional.py:231)\n]] [Op:__inference_train_function_3520]\n\nErrors may have originated from an input operation.\nInput Source operations connected to node sequential/conv2d/Conv2D:\nIn[0] sequential/random_zoom/transform/ImageProjectiveTransformV3 (defined at /usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/image_preprocessing.py:700)\t\nIn[1] sequential/conv2d/Conv2D/ReadVariableOp:\n\nOperation defined at: (most recent call last)\n>>>   File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n>>>     return _run_code(code, main_globals, None,\n>>> \n>>>   File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n>>>     exec(code, run_globals)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel_launcher.py\", line 16, in <module>\n>>>     app.launch_new_instance()\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py\", line 846, in launch_instance\n>>>     app.start()\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/kernelapp.py\", line 677, in start\n>>>     self.io_loop.start()\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py\", line 199, in start\n>>>     self.asyncio_loop.run_forever()\n>>> \n>>>   File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n>>>     self._run_once()\n>>> \n>>>   File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n>>>     handle._run()\n>>> \n>>>   File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n>>>     self._context.run(self._callback, *self._args)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py\", line 457, in dispatch_queue\n>>>     await self.process_one()\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py\", line 446, in process_one\n>>>     await dispatch(*args)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py\", line 353, in dispatch_shell\n>>>     await result\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py\", line 648, in execute_request\n>>>     reply_content = await reply_content\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/ipkernel.py\", line 353, in do_execute\n>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/zmqshell.py\", line 533, in run_cell\n>>>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py\", line 2901, in run_cell\n>>>     result = self._run_cell(\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n>>>     return runner(coro)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n>>>     coro.send(None)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py\", line 3172, in run_cell_async\n>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n>>>     if (await self.run_code(code, result,  async_=asy)):\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n>>>     exec(code_obj, self.user_global_ns, self.user_ns)\n>>> \n>>>   File \"/tmp/ipykernel_26940/2573111011.py\", line 2, in <module>\n>>>     execute_model(model)\n>>> \n>>>   File \"/tmp/ipykernel_26940/4047184360.py\", line 157, in execute_model\n>>>     history = model.fit(train_images, train_labels, epochs=200,\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1216, in fit\n>>>     tmp_logs = self.train_function(iterator)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 878, in train_function\n>>>     return step_function(self, iterator)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 867, in step_function\n>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 860, in run_step\n>>>     outputs = model.train_step(data)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 808, in train_step\n>>>     y_pred = self(x, training=True)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/sequential.py\", line 373, in call\n>>>     return super(Sequential, self).call(inputs, training=training, mask=mask)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py\", line 451, in call\n>>>     return self._run_internal_graph(\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n>>>     outputs = node.layer(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/layers/convolutional.py\", line 246, in call\n>>>     outputs = self.convolution_op(inputs, self.kernel)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/layers/convolutional.py\", line 231, in convolution_op\n>>>     return tf.nn.convolution(\n>>> ",
          "output_type": "error",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mNotFoundError\u001b[0m                             Traceback (most recent call last)",
            "\u001b[0;32m/tmp/ipykernel_26940/2573111011.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0mmodel\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mlstm_model\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mexecute_model\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mmodel\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
            "\u001b[0;32m/tmp/ipykernel_26940/4047184360.py\u001b[0m in \u001b[0;36mexecute_model\u001b[0;34m(model)\u001b[0m\n\u001b[1;32m    155\u001b[0m             \u001b[0mloss\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mtf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mkeras\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlosses\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mSparseCategoricalCrossentropy\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfrom_logits\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    156\u001b[0m             metrics=['accuracy'])    \n\u001b[0;32m--> 157\u001b[0;31m     history = model.fit(train_images, train_labels, epochs=200,\n\u001b[0m\u001b[1;32m    158\u001b[0m                     validation_data=(test_images, test_labels))\n\u001b[1;32m    159\u001b[0m     \u001b[0mplt\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mplot\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mhistory\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mhistory\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m'accuracy'\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlabel\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m'accuracy'\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;32m/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\u001b[0m in \u001b[0;36merror_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m     65\u001b[0m     \u001b[0;32mexcept\u001b[0m \u001b[0mException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m  \u001b[0;31m# pylint: disable=broad-except\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     66\u001b[0m       \u001b[0mfiltered_tb\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0m_process_traceback_frames\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m__traceback__\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 67\u001b[0;31m       \u001b[0;32mraise\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwith_traceback\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfiltered_tb\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m     68\u001b[0m     \u001b[0;32mfinally\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     69\u001b[0m       \u001b[0;32mdel\u001b[0m \u001b[0mfiltered_tb\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;32m/usr/local/lib/python3.8/dist-packages/tensorflow/python/eager/execute.py\u001b[0m in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     56\u001b[0m   \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m     57\u001b[0m     \u001b[0mctx\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mensure_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m---> 58\u001b[0;31m     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\n\u001b[0m\u001b[1;32m     59\u001b[0m                                         inputs, attrs, num_outputs)\n\u001b[1;32m     60\u001b[0m   \u001b[0;32mexcept\u001b[0m \u001b[0mcore\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_NotOkStatusException\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0me\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
            "\u001b[0;31mNotFoundError\u001b[0m:  No algorithm worked!\n\t [[node sequential/conv2d/Conv2D\n (defined at /usr/local/lib/python3.8/dist-packages/keras/layers/convolutional.py:231)\n]] [Op:__inference_train_function_3520]\n\nErrors may have originated from an input operation.\nInput Source operations connected to node sequential/conv2d/Conv2D:\nIn[0] sequential/random_zoom/transform/ImageProjectiveTransformV3 (defined at /usr/local/lib/python3.8/dist-packages/keras/layers/preprocessing/image_preprocessing.py:700)\t\nIn[1] sequential/conv2d/Conv2D/ReadVariableOp:\n\nOperation defined at: (most recent call last)\n>>>   File \"/usr/lib/python3.8/runpy.py\", line 194, in _run_module_as_main\n>>>     return _run_code(code, main_globals, None,\n>>> \n>>>   File \"/usr/lib/python3.8/runpy.py\", line 87, in _run_code\n>>>     exec(code, run_globals)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel_launcher.py\", line 16, in <module>\n>>>     app.launch_new_instance()\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/traitlets/config/application.py\", line 846, in launch_instance\n>>>     app.start()\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/kernelapp.py\", line 677, in start\n>>>     self.io_loop.start()\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/tornado/platform/asyncio.py\", line 199, in start\n>>>     self.asyncio_loop.run_forever()\n>>> \n>>>   File \"/usr/lib/python3.8/asyncio/base_events.py\", line 570, in run_forever\n>>>     self._run_once()\n>>> \n>>>   File \"/usr/lib/python3.8/asyncio/base_events.py\", line 1859, in _run_once\n>>>     handle._run()\n>>> \n>>>   File \"/usr/lib/python3.8/asyncio/events.py\", line 81, in _run\n>>>     self._context.run(self._callback, *self._args)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py\", line 457, in dispatch_queue\n>>>     await self.process_one()\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py\", line 446, in process_one\n>>>     await dispatch(*args)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py\", line 353, in dispatch_shell\n>>>     await result\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/kernelbase.py\", line 648, in execute_request\n>>>     reply_content = await reply_content\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/ipkernel.py\", line 353, in do_execute\n>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/ipykernel/zmqshell.py\", line 533, in run_cell\n>>>     return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py\", line 2901, in run_cell\n>>>     result = self._run_cell(\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py\", line 2947, in _run_cell\n>>>     return runner(coro)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/async_helpers.py\", line 68, in _pseudo_sync_runner\n>>>     coro.send(None)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py\", line 3172, in run_cell_async\n>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py\", line 3364, in run_ast_nodes\n>>>     if (await self.run_code(code, result,  async_=asy)):\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py\", line 3444, in run_code\n>>>     exec(code_obj, self.user_global_ns, self.user_ns)\n>>> \n>>>   File \"/tmp/ipykernel_26940/2573111011.py\", line 2, in <module>\n>>>     execute_model(model)\n>>> \n>>>   File \"/tmp/ipykernel_26940/4047184360.py\", line 157, in execute_model\n>>>     history = model.fit(train_images, train_labels, epochs=200,\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 1216, in fit\n>>>     tmp_logs = self.train_function(iterator)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 878, in train_function\n>>>     return step_function(self, iterator)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 867, in step_function\n>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 860, in run_step\n>>>     outputs = model.train_step(data)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/training.py\", line 808, in train_step\n>>>     y_pred = self(x, training=True)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/sequential.py\", line 373, in call\n>>>     return super(Sequential, self).call(inputs, training=training, mask=mask)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py\", line 451, in call\n>>>     return self._run_internal_graph(\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/functional.py\", line 589, in _run_internal_graph\n>>>     outputs = node.layer(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/engine/base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/utils/traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/layers/convolutional.py\", line 246, in call\n>>>     outputs = self.convolution_op(inputs, self.kernel)\n>>> \n>>>   File \"/usr/local/lib/python3.8/dist-packages/keras/layers/convolutional.py\", line 231, in convolution_op\n>>>     return tf.nn.convolution(\n>>> "
          ]
        }
      ],
      "source": [
        "model = lstm_model()\n",
        "execute_model(model)"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": []
    },
    {
      "cell_type": "code",
      "execution_count": null,
      "metadata": {},
      "outputs": [],
      "source": []
    }
  ],
  "metadata": {
    "accelerator": "GPU",
    "colab": {
      "collapsed_sections": [],
      "name": "cnn.ipynb",
      "provenance": [],
      "toc_visible": true
    },
    "kernelspec": {
      "display_name": "Python 3",
      "name": "python3"
    },
    "language_info": {
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "file_extension": ".py",
      "mimetype": "text/x-python",
      "name": "python",
      "nbconvert_exporter": "python",
      "pygments_lexer": "ipython3",
      "version": "3.8.10"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 0
}
